spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres-user
    password: postgres-1234
    driverClassName: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always

file:
  path: tmp
  name-prefix: source_user_

remote:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres-user
    password: postgres-1234
    driverClassName: org.postgresql.Driver
  dump:
    file:
      path: tmp
      name: remote_user.csv