spring:
  application:
    name: '@project.name@'
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres-user
    password: postgres-1234
    driverClassName: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always
fileName: feladat_1.csv